FROM ubuntu:14.04


RUN apt-get -y install software-properties-common

RUN apt-add-repository "deb http://us.archive.ubuntu.com/ubuntu trusty main multiverse"

RUN apt-get -y install software-properties-common

RUN apt-get -y update && apt-get install -y bowtie2

RUN apt-get install -y samtools

RUN apt-get install -y tophat

RUN apt-get install -y cufflinks

RUN apt-get install -y r-base

RUN apt-get install -y r-bioc-cummerbund

COPY cummerbund_plot_scripts.r /usr/local/bin/

COPY rna_seq_4_conditions_docker.py /usr/local/bin/

RUN chmod +x /usr/local/bin/rna_seq_4_conditions_docker.py

RUN chmod +x /usr/local/bin/cummerbund_plot_scripts.r

ENTRYPOINT ["python3", "/usr/local/bin/rna_seq_4_conditions_docker.py"]


