---
- hosts: condor-workers

  tasks:
  - name: install docker on workers
    apt: name=docker-engine state=present

- hosts: condor-manager

  tasks:
  - name: install condor on the manager
    apt: name=condor state=present

- hosts: condor:&ubuntu-xenial:!condor-manager

  tasks:
  - name: install condor for all ubuntu nodes
    apt: name=condor state=present
  # i am relatively confident that's a refusal from something in Erik's docs cause i don't actually see that rule in all the machines
  #- name: update iptables
    #iptables: action=append chain=INPUT protocol=tcp source=10.0.72.0/24 destination_port=5000:6000

- hosts: condor:&centos7

  tasks:
  - name: disable selinux
    selinux: state=disabled
  - name: install htcondor repositories
    get_url: url=https://research.cs.wisc.edu/htcondor/yum/repo.d/htcondor-stable-rhel7.repo dest=/etc/yum.repos.d
  - name: import condor key 
    rpm_key: state=present key=http://research.cs.wisc.edu/htcondor/yum/RPM-GPG-KEY-HTCondor
  - name: install condor for all centos nodes
    yum: name=condor.x86_64 state=present

- hosts: condor-manager
  vars_files:
  - /home/ubuntu/cyvars.yaml

  tasks:
  - name: change condor config for manager
    lineinfile: 
      backup: yes 
      path: /etc/condor/condor_config 
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
 with_items:
      - { regexp: '^CONDOR_HOST =', line: "CONDOR_HOST = {{ manager_ip }}" }  ########
      - { regexp: '^COLLECTOR_HOST =', line: 'COLLECTOR_HOST = $(CONDOR_HOST):4080?sock=collector' }
      - { regexp: '^DAEMON_LIST =', line: 'DAEMON_LIST = MASTER, SCHEDD, NEGOTIATOR, COLLECTOR, SHARED_PORT' } #####sort out this
      - { regexp: '^USE_SHARED_PORT =', line: 'USE_SHARED_PORT = True' }
      - { regexp: '^SHARED_PORT_ARGS =', line: 'SHARED_PORT_ARGS = -p 4080' }
      - { regexp: '^LOWPORT =', line: 'LOWPORT = 4080' }
      - { regexp: '^HIGHPORT =', line: 'HIGHPORT = 5080' }
    notify:
      - restart condor
  handlers:
    - name: restart condor
      service: name=condor state=restarted
      become: yes 
      become_method: sudo

- hosts: condor-workers
  vars_files:
  - /home/ubuntu/cyvars.yaml

  tasks:
  - name: change condor config for workers
    lineinfile:
      backup: yes 
      path: /etc/condor/condor_config
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    with_items:
      - { regexp: '^NETWORK_INTERFACE =', line: 'NETWORK_INTERFACE = etho.1030' }
      - { regexp: '^CONDOR_HOST =', line: "CONDOR_HOST = {{ manager_ip }}" }  ########
      - { regexp: '^COLLECTOR_HOST =', line: 'COLLECTOR_HOST = $(CONDOR_HOST):4080?sock=collector' }
      - { regexp: '^SCHEDD_HOST =', line: 'SCHEDD_HOST = submit' }
      - { regexp: '^SLOT_TYPE_1 =', line: 'SLOT_TYPE_1 = cpus=100%,disk=100%,swap=100%' }
      - { regexp: '^SLOT_TYPE_1_PARTITIONABLE =', line: 'SLOT_TYPE_1_PARTITIONABLE = True' }
      - { regexp: '^DAEMON_LIST =', line: 'DAEMON_LIST = MASTER, STARTD' }
      - { regexp: '^LOWPORT =', line: 'LOWPORT = 5000' }
      - { regexp: '^HIGHPORT =', line: 'HIGHPORT = 6000' }
      - { regexp: '^DOCKER =', line: 'DOCKER = /usr/bin/docker' }
    notify:
      - restart condor
  handlers:
    - name: restart condor
      service: name=condor state=restarted
      become: yes 
      become_method: sudo

- hosts: condor-submit:&centos7
  vars_files:
  - /home/ubuntu/cyvars.yaml

  tasks:
  - name: change condor config for submit centos nodes
    lineinfile:
      backup: yes
      path: /etc/condor/condor_config
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    with_items:
      - { regexp: '^CONDOR_HOST =', line: "CONDOR_HOST = {{ manager_ip }}" } ######
      - { regexp: '^COLLECTOR_HOST =', line: 'COLLECTOR_HOST = $(CONDOR_HOST):4080?sock=collector' }
      - { regexp: '^DAEMON_LIST =', line: 'DAEMON_LIST = MASTER, SCHEDD, SHARED_PORT' } #####sort out this
      - { regexp: '^USE_SHARED_PORT =', line: 'USE_SHARED_PORT = True' }
      - { regexp: '^SHARED_PORT_ARGS =', line: 'SHARED_PORT_ARGS = -p 4080' }
      - { regexp: '^LOWPORT =', line: 'LOWPORT = 4081' }
      - { regexp: '^HIGHPORT =', line: 'HIGHPORT = 5080' }
      - { regexp: '^ENABLE_IPV6 =', line: 'ENABLE_IPV6 = false' }
    notify:
      - restart condor
  handlers:
    - name: restart condor
      service: name=condor state=restarted
      become: yes
      become_method: sudo
